DATA:
    ROOT: '/data4/lhui/ucf'
    TRAIN_FILE: '/home/lvhui/Anomaly_Detection_splits/Anomaly_Train_multiclass.txt'
    VAL_FILE: '/home/lvhui/Anomaly_Detection_splits/Anomaly_Test_multiclass.txt'
    DATASET: ucf
    NUM_CLIPS: 32
    NUM_FRAMES: 8
    FRAME_INTERVAL: 4
    NUM_CLASSES: 2
    LABEL_LIST: 'labels/ucf_2_labels.csv'
    FILENAME_TMPL: 'img_{:08}.jpg'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 2
    ACCUMULATION_STEPS: 8